### ISSUE TITLE
Usage of webcomponent in an XML Fragment of an SAPUI5 Fiori Elements App

### ISSUE THREAD

**Issue by T1mey** [UI5/webcomponents#13453]
### Bug Description

Hi,

I've updated my webcomponent to the latest version (2.21.1) of npm packages.
Did a rebuild and published it.

We embed the webcomponent in a Fiori Elements (SAPUI5 1.147.0) over a XML Fragment and now getting an error.

`2026-05-04 10:30:40.223500 z.getAllSettings is not a function - TypeError: z.getAllSettings is not a function  
 TypeError: z.getAllSettings is not a function
    at fe (XMLTemplateProcessor-dbg.js:1296:35)
    at XMLTemplateProcessor-dbg.js:1234:14`

Read all readme and blogs and can't find any hint. Is there a problem or do I miss something?

### Steps to Reproduce

1.
2.
3.
...

### Priority

None

### UI5 Web Components Version

2.21.1

### Browser

Chrome

### Operating System

Win

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by nnaydenow** [comment]
Hi @T1mey,

The issue sounds more related to the OpenUI5. Could you please recreate it in https://github.com/UI5/openui5/?

Also please share more details when opening the incident like OpenUI5 version and etc.

Regards,
Nayden

**Comment by petermuessig** [comment]
I'm not sure whether this is an OpenUI5 issue or related to the `ui5-tooling-modules` middleware. Maybe the generated custom elements manifest is the problem or an issue in the generation of the wrapper. Need to be investigated deeper...

**Comment by petermuessig** [comment]
@nnaydenow : the custom-elements-internal.json isn't built anymore - this is the problem. Does this need to be generated explicitly now?

**Comment by nnaydenow** [comment]
Hi @T1mey,

After taking a closer look, I identified a regression introduced with #12851.

I’ll prepare a fix for it.

In the meantime, you can apply the following workaround by adding these lines to your `package-script.js`:

```js
...
const scripts = getScripts(options);

const tsOption = !!(!options.legacy || options.jsx);
scripts.prepare.default = `${scripts.prepare.default} generateAPI`,
scripts.generateAPI.default = tsOption ? "ui5nps generateAPI.generateCEM generateAPI.validateCEM generateAPI.mergeCEM" : "";
...
```
